// src/lib/mock-preset.ts
export const mockGeminiResponse = {
  "skull width": 50,
  "skull height": 50,
  "temple morphology": 50,
  "eyebrow center height": 50,
  "eyebrow center thickness": 16,
  "interbrow distance": 73,
  "central eyelid fold thickness": 62,
  "central eyelid fold height": 50,
  "central eyelid fold depth": 65,
  "central eyelid fold size": 56,
  "outer eyelid fold thickness": 34,
  "outer eyelid fold height": 96,
  "outer eyelid fold depth": 47,
  "outer eyelid fold size": 18,
  "inner eyelid fold thickness": 34,
  "inner eyelid fold height": 96,
  "inner eyelid fold depth": 47,
  "inner eyelid fold size": 18,
  "central lower eyelid thickness": 34,
  "central lower eyelid height": 96,
  "central lower eyelid depth": 47,
  "central lower eyelid size": 18,
  "outer lower eyelid thickness": 34,
  "outer lower eyelid height": 96,
  "outer lower eyelid depth": 47,
  "inner lower eyelid width narrow expand": 56,
  "inner lower eyelid height position": 57,
  "inner lower eyelid scale size": 57,
  "central upper eyelid width narrow expand": 25,
  "central upper eyelid height position": 72,
  "central upper eyelid depth projection": 0,
  "central upper eyelid scale size": 50,
  "outer upper eyelid width narrow expand": 35,
  "outer upper eyelid height position": 85,
  "outer upper eyelid scale size": 59,
  "inner upper eyelid width narrow expand": 56,
  "inner upper eyelid height position": 44,
  "inner upper eyelid scale size": 52,
  "outer eye corner canthus width narrow expand": 49,
  "outer eye corner canthus height position": 77,
  "outer eye corner canthus scale size": 17,
  "inner eye corner canthus width narrow expand": 55,
  "inner eye corner canthus height position": 42,
  "inner eye corner canthus scale size": 33,
  "outer upper ear helix width narrow expand": 63,
  "outer upper ear helix height position": 69,
  "outer upper ear helix depth projection": 83,
  "outer central ear concha width narrow expand": 59,
  "outer central ear concha height position": 33,
  "outer central ear concha depth projection": 67,
  "outer lower ear lobe width narrow expand": 17,
  "outer lower ear lobe height position": 36,
  "outer lower ear lobe depth projection": 69,
  "inner upper ear antihelix width narrow expand": 43,
  "inner upper ear antihelix height position": 47,
  "inner upper ear antihelix depth projection": 70,
  "inner lower ear antitragus width narrow expand": 82,
  "inner lower ear antitragus height position": 70,
  "inner lower ear antitragus depth projection": 70,
  "earlobe width narrow expand": 8,
  "earlobe height position": 44,
  "earlobe depth projection": 95,
  "ear tragus width narrow expand": 0,
  "ear tragus height position": 46,
  "ear tragus depth projection": 90,
  "upper nostrils width narrow expand": 42,
  "upper nostrils height position": 50,
  "upper nostrils depth projection": 67,
  "upper nostrils shape round angular definition": 20,
  "outer upper nostrils width narrow expand": 31,
  "outer upper nostrils height position": 83,
  "outer upper nostrils depth projection": 32,
  "outer upper nostrils shape round angular definition": 17,
  "central upper nostrils width narrow expand": 52,
  "central upper nostrils height position": 19,
  "central upper nostrils depth projection": 84,
  "central upper nostrils shape round angular definition": 0,
  "lower nostrils width narrow expand": 50,
  "lower nostrils height position": 45,
  "lower nostrils depth projection": 71,
  "lower nostrils shape round angular definition": 95,
  "outer lower nostrils width narrow expand": 3,
  "outer lower nostrils height position": 98,
  "outer lower nostrils depth projection": 67,
  "outer lower nostrils shape round angular definition": 24,
  "central lower nostrils width narrow expand": 83,
  "central lower nostrils height position": 87,
  "central lower nostrils depth projection": 14,
  "central lower nostrils shape round angular definition": 39,
  "upper nose tip width narrow expand": 36,
  "upper nose tip height position": 93,
  "upper nose tip depth projection": 63,
  "upper nose tip shape round angular definition": 69,
  "upper nose tip horizontal shift position": 57,
  "lower nose tip width narrow expand": 43,
  "lower nose tip height position": 12,
  "lower nose tip depth projection": 96,
  "lower nose tip shape round angular definition": 10,
  "lower nose tip horizontal shift position": 67,
  "bottom nose tip width narrow expand": 41,
  "bottom nose tip height position": 45,
  "bottom nose tip depth projection": 85,
  "bottom nose tip shape round angular definition": 82,
  "bottom nose tip horizontal shift position": 58,
  "cheekbone height vertical position": 81,
  "cheek volume fullness prominence": 35,
  "outer upper cheek volume fullness prominence": 58,
  "inner upper cheek suborbital height position": 65,
  "inner upper cheek suborbital volume fullness": 62,
  "inner upper cheek volume fullness prominence": 30,
  "outer lower cheek hollow reduction prominence": 50,
  "inner lower cheek reduction prominence": 50,
  "mouth corners width narrow expand": 55,
  "mouth corners height vertical position": 76,
  "mouth corners depth projection": 42,
  "mouth corners shape round angular definition": 41,
  "center mouth interlabial gap width narrow expand": 45,
  "center mouth interlabial gap height position": 50,
  "center mouth interlabial gap depth projection": 21,
  "center mouth interlabial gap shape round angular definition": 86,
  "lateral mouth interlabial gap width narrow expand": 22,
  "lateral mouth interlabial gap height position": 46,
  "lateral mouth interlabial gap depth projection": 32,
  "lateral mouth interlabial gap shape round angular definition": 35,
  "upper center upper lip width narrow expand": 16,
  "upper center upper lip height position": 54,
  "upper center upper lip depth projection": 51,
  "upper center upper lip shape round angular definition": 25,
  "upper center upper lip horizontal shift position": 69,
  "upper lateral upper lip width narrow expand": 58,
  "upper lateral upper lip height position": 62,
  "upper lateral upper lip depth projection": 51,
  "upper lateral upper lip shape round angular definition": 50,
  "upper outer corners upper lip width narrow expand": 20,
  "upper outer corners upper lip height position": 66,
  "upper outer corners upper lip depth projection": 47,
  "upper outer corners upper lip shape round angular definition": 34,
  "lower center upper lip width narrow expand": 93,
  "lower center upper lip height position": 48,
  "lower center upper lip depth projection": 29,
  "lower center upper lip shape round angular definition": 38,
  "lower center upper lip horizontal shift position": 61,
  "lower lateral upper lip width narrow expand": 35,
  "lower lateral upper lip height position": 33,
  "lower lateral upper lip depth projection": 30,
  "lower lateral upper lip shape round angular definition": 64,
  "upper lip fullness volume thickness narrow expand": 39,
  "upper lip fullness volume vertical height position": 52,
  "upper lip fullness volume depth protrusion": 42,
  "upper lip fullness volume shape round angular definition": 50,
  "philtrum dimple column width narrow expand": 69,
  "philtrum vertical length height position": 87,
  "philtrum ridge depth projection prominence": 100,
  "philtrum definition shape round angular": 70,
  "philtrum horizontal shift deviation position": 69,
  "lower lip fullness volume thickness narrow expand": 51,
  "lower lip fullness volume vertical height position": 48,
  "lower lip fullness volume depth protrusion": 26,
  "lower lip fullness volume shape round angular definition": 26,
  "upper center lower lip width narrow expand": 30,
  "upper center lower lip height position": 35,
  "upper center lower lip depth projection": 16,
  "upper center lower lip shape round angular definition": 47,
  "upper center lower lip horizontal shift position": 47,
  "upper lateral lower lip width narrow expand": 43,
  "upper lateral lower lip height position": 25,
  "upper lateral lower lip depth projection": 21,
  "upper lateral lower lip shape round angular definition": 84,
  "bottom center lower lip width narrow expand": 0,
  "bottom center lower lip height position": 62,
  "bottom center lower lip depth projection": 10,
  "bottom center lower lip shape round angular definition": 85,
  "bottom center lower lip horizontal shift position": 60,
  "bottom lateral lower lip width narrow expand": 54,
  "bottom lateral lower lip height position": 45,
  "bottom lateral lower lip depth projection": 31,
  "bottom lateral lower lip shape round angular definition": 83,
  "bottom outer corners lower lip width narrow expand": 30,
  "bottom outer corners lower lip height position": 37,
  "bottom outer corners lower lip depth projection": 40,
  "bottom outer corners lower lip shape round angular definition": 82,
  "mouth corners marionette lines wrinkles intensity reduction": 50,
  "chin dimple cleft vertical height position": 64,
  "chin dimple cleft horizontal shift position": 42,
  "chin lateral pads width reduction prominence": 50,
  "jawline mandible bone width prominence": 19
}
